### ISSUE TITLE
For the sake of helpful feedback

### ISSUE THREAD

**Issue by Ebren100** [theHostileNegotiator/KWBandage#2] opened 2020-11-22 09:26 UTC
Thanks for responding! I think I have found more small issues, I hope you're happy for more feedback. Again i love KWBandage. 

As a lazy fix for the EMP abilities, you can add the UpdateTime="15s" into <AISpecialPowerUpdate  and they will only use the ability every 15 seconds, but may be less proactive when waiting for this timer to expire I'm guessing. 

As for other issues, I noticed some problems when I implemented your mod but I also changed some things so these issues may have been inadvertently added by me and not you (I don't know how though)

Reaper17's Nerve Center doesn't have the forcefields upgrade

Zone Shatterers don't have stances (can easily add the generic stance code to them if this really is an issue)

 I've found that Tib Vein Detonation can crash the game? Not sure if other people have had this. It used to happen on console version too so I doubt I can blame the mod. 

Thanks again

**Comment by theHostileNegotiator** [comment] 2020-11-23 02:44
> As a lazy fix for the EMP abilities, you can add the UpdateTime="15s" into <AISpecialPowerUpdate and they will only use the ability every 15 seconds, but may be less proactive when waiting for this timer to expire I'm guessing.

I'm not willing to commit to that

> Reaper17's Nerve Center doesn't have the forcefields upgrade

Works as intended on my end

> Zone Shatterers don't have stances

Should be fixed now

> I've found that Tib Vein Detonation can crash the game

Never heard of this before. Do you have some footage, documentation or a way of recreating

**Closed as completed** 2020-11-24 08:56 UTC
